/*QUERY RICORSIVE*/

/*REQUISITO: NELLA RELAZIONE DATA (TABELLA_DI_INIZIALIZZAZIONE) CI DEVE ESSERE UN RIFERIMENTO (FK) ALLA RELAZIONE STESSA*/

/*
PER PRIMA COSA SI DEVE DEFINIRE IN MODO RICORSIVO UNA TABELLA (NOME_TABELLA) SU CUI FARE LA QUERY

SI DEFINISCE USANDO LE COMMON TABLE EXPRESSIONS CON LA KEYWORD WITH 

DEVE CONTENERE COME COLONNE LA CHIAVE (PK) DELLA RELAZIONE E IL RIFERIMENTO (FK)

TABELLA_DI_INIZIALIZZAZIONE

----------------------------------------------
| CHIAVE | ATTR1 | ATTR2 | ... | RIFERIMENTO |
----------------------------------------------
|...     | ...   | ...   | ... | ...         |      
----------------------------------------------
|...     | ...   | ...   | ... | ...         |
----------------------------------------------
|...     | ...   | ...   | ... | ...         |
----------------------------------------------

RIFERIMENTO REFERENCES TABELLA_DI_INIZIALIZZAZIONE

NOME_TABELLA 

---------------------
| SUB_FOO | SUP_FOO |
---------------------
|    ...  |  ...    |
---------------------
|    ...  |  ...    |
---------------------

SUB_FOO = CHIAVE 
SUP_FOO = RIFERIMENTO
*/

WITH NOME_TABELLA(SUB_FOO, SUP_FOO) AS --USARE SUB E SUP NEI NOMI COLONNE
(
    --QUERY BASE (STANDARD)
    (
        SELECT CHIAVE, RIFERIMENTO
        FROM TABELLA_DI_INIZIALIZZAZIONE
        WHERE RIFERIMENTO IS NOT NULL --CI VA SEMPRE
    ) 
    UNION ALL 
    --QUERY RICORSIVA 
    --BISOGNA SEMPRE INCROCIARE CHIAVE E RIFERIMENTO DELLA TABELLA_DI_INIZIALIZZAZIONE CON SUB_FOO E SUP_FOO DELLA NOME_TABELLA
    --DUE NELLA SELECT (UNA DA TABELLA_DI_INIZIALIZZAZIONE E UNA DA NOME_TABELLA) E DUE (UNA DA TABELLA_DI_INIZIALIZZAZIONE E UNA DA NOME_TABELLA) NEL JOIN 
    (
        SELECT TABELLA_DI_INIZIALIZZAZIONE.CHIAVE, NOME_TABELLA.SUP_FOO
        FROM NOME_TABELLA --CONSIGLIATO METTERE UN ALIAS
                JOIN TABELLA_DI_INIZIALIZZAZIONE ON (NOME_TABELLA.SUB_FOO = TABELLA_DI_INIZIALIZZAZIONE.RIFERIMENTO)
        WHERE TABELLA_DI_INIZIALIZZAZIONE.RIFERIMENTO IS NOT NULL --CI VA SEMPRE
    ) 
) 

/*A QUESTO PUNTO DOPO AVER CREATO LA TABELLA RICORSIVA POSSO FARCI LA QUERY SOPRA (USANDO NOME_TABELLA) NORMALMENTE

IS NOT NULL CI VA SIA NELLA QUERY BASE CHE IN QUELLA RICORSIVA PER EVITARE I VALORI NULL IN USCITA */