--1. Inserire un controllo in tabella ISCRITTO che garantisca che una competizione non possa avere più artisti classificati nella stessa posizione.

ALTER TABLE ISCRITTO 
ADD CONSTRAINT UNIQUE_ARTISTA_COMPETIZIONE_POSIZIONE UNIQUE(NOMECOMP, ANNOEDIZIONE, INTERPRETE, POSIZIONE)

--2. Inserire un controllo che l'attributo ANNOEDIZIONE in tabella COMPETIZIONE sia compreso tra 1970 e 2050.

ALTER TABLE COMPETIZIONE 
ADD CONSTRAINT CHECK_ANNOEDIZIONE CHECK(ANNOEDIZIONE BETWEEN 1970 AND 2050)

--3. Selezionare i dati dei vincitori sul podio (primo, secondo e terzo classificato) di ogni COMPETIZIONE svoltasi a Bologna.

SELECT IN1.*, IN2.*, IN3.*, C.NOMECOMP, C.ANNOEDIZIONE
FROM COMPETIZIONE C 
        JOIN ISCRITTO I1 ON (I1.NOMECOMP = C.NOMECOMP AND I1.ANNOEDIZIONE = C.ANNOEDIZIONE)
        JOIN ISCRITTO I2 ON (I2.NOMECOMP = C.NOMECOMP AND I2.ANNOEDIZIONE = C.ANNOEDIZIONE)
        JOIN ISCRITTO I3 ON (I3.NOMECOMP = C.NOMECOMP AND I3.ANNOEDIZIONE = C.ANNOEDIZIONE)
        JOIN INTERPRETE IN1 ON (I1.INTERPRETE = IN1.NOME)
        JOIN INTERPRETE IN2 ON (I2.INTERPRETE = IN2.NOME)
        JOIN INTERPRETE IN3 ON (I3.INTERPRETE = IN3.NOME)
WHERE I1.POSIZIONE = 1
AND I2.POSIZIONE = 2 
AND I3.POSIZIONE = 3
AND C.LUOGO = 'BOLOGNA'

/*OPPURE
SELECT IT.*
FROM COMPETIZIONE C 
        JOIN ISCRITTO I ON (C.NOMECOMP = I.NOMECOMP AND C.ANNOEDIZIONE = I.ANNOEDIZIONE)
        JOIN INTERPRETE IT ON (I.INTERPRETE = IT.NOME)
WHERE C.LUOGO = 'BOLOGNA'
AND I.POSIZIONE <= 3
*/

--4. Selezionare le competizioni in cui non c'è stato nessun ritirato.

SELECT *
FROM COMPETIZIONE C 
WHERE NOT EXISTS(
    SELECT *
    FROM COMPETIZIONE C1 
            JOIN ISCRITTO I ON (C1.NOMECOMP = I.NOMECOMP AND C1.ANNOEDIZIONE = I.ANNOEDIZIONE)
    WHERE I.POSIZIONE IS NULL
    AND C1.NOMECOMP = C.NOMECOMP
    AND C1.ANNOEDIZIONE = C.ANNOEDIZIONE
)

--5. Selezionare nome e data di nascita degli interpreti che hanno partecipato a tutte le edizioni di FESTIVALBAR.

SELECT NOME, DATA_NASCITA
FROM INTERPRETE IN1
WHERE NOT EXISTS(
    SELECT *
    FROM COMPETIZIONE C 
    WHERE C.NOMECOMP = 'FESTIVALBAR'
    AND NOT EXISTS(
        SELECT *
        FROM ISCRITTO I
        WHERE I.NOMECOMP = C.NOMECOMP
        AND I.ANNOEDIZIONE = C.ANNOEDIZIONE
        AND I.INTERPRETE = IN1.NOME
    )
)
